In [1]:
#1_question
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vector = np. zeros(10); x[4] = 1
print(vector)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2_question
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
vector_2 = np.arange(10,49)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
#3_question
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix = np.arange(0,9).reshape(3,3) 
print(matrix)                                                


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#4_question
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr=np.nonzero([1,2,0,0,4,0])
arr

(array([0, 1, 4], dtype=int64),)

In [4]:
#5_question
#Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
arr1=np.random.rand(10,10)
arr1_min=arr1.min()
arr1_max=arr1.max()
print(arr1_min,arr1_max)


0.012920400066484428 0.9963379973268094


In [3]:
#6_question
#Create a random vector of size 30 and find the mean value.
import numpy as np
vect1=np.random.random(30)
mean=vect1.mean()
mean

0.5554316202632754