In [1]:
#1_question
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vector = np. zeros(10); x[4] = 1
print(vector)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2_question
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
vector_2 = np.arange(10,49)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
#3_question
# Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix = np.arange(0,9).reshape(3,3) 
print(matrix)                                                


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#4_question
#Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr=np.nonzero([1,2,0,0,4,0])
arr

(array([0, 1, 4], dtype=int64),)

In [13]:
#5_question
#Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
arr1=np.random.rand(10,10)
arr1


array([[0.64940032, 0.70236353, 0.77089352, 0.86717971, 0.87393038,
        0.76907138, 0.63733516, 0.14148069, 0.78818161, 0.86075397],
       [0.6299868 , 0.27740807, 0.64116885, 0.36600827, 0.3572452 ,
        0.59432022, 0.18401394, 0.77347949, 0.10485433, 0.11612185],
       [0.39718271, 0.02470479, 0.23997199, 0.87039177, 0.64612981,
        0.03760819, 0.11932479, 0.82272964, 0.07983914, 0.46614245],
       [0.03889966, 0.74029964, 0.96741227, 0.30569282, 0.16473961,
        0.86521826, 0.87560471, 0.22779492, 0.0873818 , 0.67653904],
       [0.85094782, 0.57081266, 0.67784568, 0.18384966, 0.30330355,
        0.55392879, 0.86788344, 0.8619422 , 0.9542496 , 0.75551677],
       [0.67427382, 0.53556088, 0.29568282, 0.31911906, 0.31586957,
        0.66247936, 0.55389247, 0.08892099, 0.40332339, 0.93244045],
       [0.93416342, 0.80822397, 0.59152747, 0.71139026, 0.25052602,
        0.05377316, 0.9492309 , 0.76594133, 0.5075571 , 0.43712991],
       [0.8149159 , 0.40085002, 0.1533086

In [16]:
#6_question
#Create a random vector of size 30 and find the mean value.
import numpy as np
arr1_min=arr1.min()
arr1_max=arr1.max()
print(arr1_min,arr1_max)

0.005739602786227316 0.9910165622513029
